/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import Utilities.ConnectionWithServer;
import Utilities.FunctionsBitalino;
import java.awt.Color;

/**
 *
 * @author carmen
 */
public class PatientBitalinoWindow extends javax.swing.JFrame {
    public PatientBitalinoWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.MacError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MacInput = new javax.swing.JTextField();
        MacError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SaveBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackBut.setText("Not now");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        jLabel1.setText("INSERT YOUR BITALINO MAC:");

        MacInput.setText("98:D1:91:FD:69:49");
        MacInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacInputActionPerformed(evt);
            }
        });

        MacError.setText("This is not a MAC adress");

        jLabel3.setText("aa:aa:aa:aa:aa:aa");

        SaveBut.setText("Save");
        SaveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackBut)
                        .addGap(114, 114, 114)
                        .addComponent(SaveBut)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MacError)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(MacInput, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MacInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MacError)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBut)
                    .addComponent(SaveBut))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MacInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacInputActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MacInputActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
      ConnectionWithServer.sendSomething(FirstWindow.socket, FirstWindow.printWriter, "back");
      PatientInsideWindow rd = new PatientInsideWindow();
      this.setVisible(false);
      rd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BackButActionPerformed

    private void SaveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButActionPerformed
        boolean e = checkMacInterface();
        if (!e) {
            PatientInsideWindow rd = new PatientInsideWindow();
            this.setVisible(false);
            rd.setVisible(true);
        }
    }//GEN-LAST:event_SaveButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientBitalinoWindow().setVisible(true);
            }
        });
    }

    public boolean checkMacInterface() {
        boolean errorMac = false;
        String macAddress = this.MacInput.getText();
        if (!FunctionsBitalino.checkMac(macAddress)) {
            this.MacError.setForeground(Color.red);
            this.MacError.setVisible(true);
            errorMac = true;
        } else {
            this.MacError.setVisible(false);
            errorMac = false;
        }
        if (!errorMac) {
            PatientPrincipalWindow.patient.setMacBitalino(macAddress);
            System.out.println(PatientPrincipalWindow.patient.getMacBitalino().toString());
            ConnectionWithServer.sendSomething(FirstWindow.socket, FirstWindow.printWriter, macAddress);
            System.out.println(PatientPrincipalWindow.patient.getID());
            ConnectionWithServer.receiveData(FirstWindow.socket, FirstWindow.bufferedReader);
        }
        return errorMac;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel MacError;
    private javax.swing.JTextField MacInput;
    private javax.swing.JButton SaveBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
